# Generated by Django 4.2.1 on 2023-05-08 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.CharField(
                max_length=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.CharField(
                max_length=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
