# Generated by Django 4.2.1 on 2023-05-04 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_alter_cartproducts_cart_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartproducts",
            old_name="cart_id",
            new_name="cart",
        ),
    ]
