# Generated by Django 4.2.1 on 2023-05-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_rename_cart_id_cartproducts_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproducts",
            name="price",
            field=models.IntegerField(default=1),
        ),
    ]
