# Generated by Django 4.2.1 on 2023-05-05 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_cartproducts_price_currency_alter_cartproducts_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproducts",
            name="quantity",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
