# Generated by Django 4.2.1 on 2023-05-08 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_stock"),
        ("products", "0004_product_image"),
    ]

    operations = []
